CREATE TABLE IF NOT EXISTS equity (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    equity_name VARCHAR(255) NOT NULL,
    symbol VARCHAR(50) NOT NULL UNIQUE,
    price DOUBLE NOT NULL,
    quantity INT NOT NULL
);
